name: Deploy to Aliyun Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置 SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
        
    - name: 添加服务器到 known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
    - name: 部署到服务器
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        ssh $SERVER_USER@$SERVER_HOST << 'ENDSSH'
          set -e
          
          cd ${{ secrets.DEPLOY_PATH }}
          
          if [ ! -d ".git" ]; then
            echo "首次部署，克隆仓库..."
            git clone https://github.com/mikelinzheyu/interview-system.git .
          fi
          
          echo "拉取最新代码..."
          git fetch origin
          git reset --hard origin/main
          
          mkdir -p logs/backend logs/frontend logs/redis logs/proxy data/redis
          
          echo "停止现有服务..."
          docker-compose down || true
          
          echo "构建并启动服务..."
          docker-compose up -d --build
          
          echo "等待服务启动..."
          sleep 10
          
          echo "检查服务状态..."
          docker-compose ps
          
          echo "清理旧镜像..."
          docker image prune -f
          
          echo "✅ 部署完成！"
        ENDSSH
        
    - name: 验证部署状态
      if: always()
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        ssh $SERVER_USER@$SERVER_HOST << 'ENDSSH'
          cd ${{ secrets.DEPLOY_PATH }}
          echo "=== 容器运行状态 ==="
          docker-compose ps
        ENDSSH
        
    - name: 部署结果通知
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "🎉 部署流程执行完成！"
          echo "前端访问地址: http://${{ secrets.SERVER_HOST }}"
          echo "后端 API 地址: http://${{ secrets.SERVER_HOST }}:8080/api"
        else
          echo "❌ 部署失败，请检查日志"
        fi
